/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tiendaderopa.Vistas;

/**
 *
 * @author valen
 */
public class HomeC extends javax.swing.JPanel {

    /**
     * Creates new form home
     */
    public HomeC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        zafiro = new javax.swing.JLabel();
        btn_ingresar = new javax.swing.JPanel();
        txt_ingresar = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        btn_registrar = new javax.swing.JPanel();
        txt_registrar = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navbar.setBackground(new java.awt.Color(0, 0, 51));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        zafiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiendaderopa/Vistas/imagenes/zafiro_50.jpg"))); // NOI18N
        zafiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navbar.add(zafiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btn_ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txt_ingresar.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        txt_ingresar.setForeground(new java.awt.Color(0, 0, 51));
        txt_ingresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_ingresar.setText("INGRESAR");
        txt_ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_ingresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btn_ingresarLayout = new javax.swing.GroupLayout(btn_ingresar);
        btn_ingresar.setLayout(btn_ingresarLayout);
        btn_ingresarLayout.setHorizontalGroup(
            btn_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_ingresarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btn_ingresarLayout.setVerticalGroup(
            btn_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_ingresarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_ingresar, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
        );

        navbar.add(btn_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, -1, -1));

        titulo.setFont(new java.awt.Font("Sylfaen", 0, 45)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("B  I  E  N  V  E  N  I  D  O");
        titulo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        navbar.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, 60));

        btn_registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txt_registrar.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        txt_registrar.setForeground(new java.awt.Color(0, 0, 51));
        txt_registrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_registrar.setText("REGISTRARSE");
        txt_registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_registrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btn_registrarLayout = new javax.swing.GroupLayout(btn_registrar);
        btn_registrar.setLayout(btn_registrarLayout);
        btn_registrarLayout.setHorizontalGroup(
            btn_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_registrar, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        btn_registrarLayout.setVerticalGroup(
            btn_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_registrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_registrar, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
        );

        navbar.add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1107, 20, 160, -1));

        fondo.add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 80));

        contenido.setBackground(new java.awt.Color(248, 248, 248));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1270, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        fondo.add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1270, 500));

        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 650));
    }// </editor-fold>//GEN-END:initComponents

    private void generarContenido(){
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_ingresar;
    private javax.swing.JPanel btn_registrar;
    private javax.swing.JPanel contenido;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel navbar;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel txt_ingresar;
    private javax.swing.JLabel txt_registrar;
    private javax.swing.JLabel zafiro;
    // End of variables declaration//GEN-END:variables


}
