/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tiendaderopa.Vistas;

/**
 *
 * @author valen
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fondo = new javax.swing.JPanel();
        fondo_form = new javax.swing.JPanel();
        inicio_S = new javax.swing.JLabel();
        tit_uc = new javax.swing.JLabel();
        nom_corr1 = new javax.swing.JTextField();
        separador1 = new javax.swing.JSeparator();
        tit_contra = new javax.swing.JLabel();
        Separador2 = new javax.swing.JSeparator();
        contrasena = new javax.swing.JPasswordField();
        btn_ingresar = new javax.swing.JPanel();
        txt_ingresar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        imagen_modelo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 650));

        fondo.setBackground(new java.awt.Color(204, 204, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo_form.setBackground(new java.awt.Color(0, 0, 51));
        fondo_form.setPreferredSize(new java.awt.Dimension(660, 650));

        inicio_S.setFont(new java.awt.Font("SimSun", 1, 50)); // NOI18N
        inicio_S.setForeground(new java.awt.Color(255, 255, 255));
        inicio_S.setText("INICIO DE SESIÓN");

        tit_uc.setFont(new java.awt.Font("Yu Gothic UI", 1, 22)); // NOI18N
        tit_uc.setForeground(new java.awt.Color(255, 255, 255));
        tit_uc.setText("USUARIO  ");

        nom_corr1.setBackground(new java.awt.Color(0, 0, 51));
        nom_corr1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        nom_corr1.setForeground(new java.awt.Color(204, 204, 204));
        nom_corr1.setText("Ingrese su nombre de usuario o correo electronico");
        nom_corr1.setBorder(null);
        nom_corr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_corr1ActionPerformed(evt);
            }
        });

        tit_contra.setFont(new java.awt.Font("Yu Gothic UI", 1, 22)); // NOI18N
        tit_contra.setForeground(new java.awt.Color(255, 255, 255));
        tit_contra.setText("CONTRASEÑA");

        contrasena.setBackground(new java.awt.Color(0, 0, 51));
        contrasena.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        contrasena.setForeground(new java.awt.Color(204, 204, 204));
        contrasena.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        contrasena.setText("Ingrese su contraseña");
        contrasena.setBorder(null);

        btn_ingresar.setBackground(new java.awt.Color(255, 255, 255));
        btn_ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ingresarMouseEntered(evt);
            }
        });

        txt_ingresar.setFont(new java.awt.Font("SimSun", 1, 20)); // NOI18N
        txt_ingresar.setForeground(new java.awt.Color(0, 0, 51));
        txt_ingresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_ingresar.setText("INGRESAR");
        txt_ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_ingresarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout btn_ingresarLayout = new javax.swing.GroupLayout(btn_ingresar);
        btn_ingresar.setLayout(btn_ingresarLayout);
        btn_ingresarLayout.setHorizontalGroup(
            btn_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_ingresar, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
        );
        btn_ingresarLayout.setVerticalGroup(
            btn_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_ingresar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fondo_formLayout = new javax.swing.GroupLayout(fondo_form);
        fondo_form.setLayout(fondo_formLayout);
        fondo_formLayout.setHorizontalGroup(
            fondo_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondo_formLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(fondo_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondo_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tit_contra)
                        .addComponent(tit_uc)
                        .addComponent(inicio_S)
                        .addComponent(separador1)
                        .addComponent(nom_corr1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                        .addComponent(Separador2)
                        .addComponent(contrasena))
                    .addComponent(btn_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        fondo_formLayout.setVerticalGroup(
            fondo_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondo_formLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(inicio_S, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(tit_uc)
                .addGap(18, 18, 18)
                .addComponent(nom_corr1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(tit_contra)
                .addGap(18, 18, 18)
                .addComponent(contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btn_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        fondo.add(fondo_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 660, 670));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiendaderopa/Vistas/imagenes/zafiroo.png"))); // NOI18N
        fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, -1, -1));

        imagen_modelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiendaderopa/Vistas/imagenes/foto_modelo2.jpg"))); // NOI18N
        fondo.add(imagen_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, -160, 780, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nom_corr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_corr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_corr1ActionPerformed

    private void txt_ingresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ingresarMouseEntered
        txt_ingresar.setBackground(new java.awt.Color(195,195,195)); // Color morado
        txt_ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_txt_ingresarMouseEntered

    private void btn_ingresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresarMouseEntered
        txt_ingresar.setBackground(new java.awt.Color(195,195,195)); // Color gris
        txt_ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_ingresarMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator Separador2;
    private javax.swing.JPanel btn_ingresar;
    private javax.swing.JPasswordField contrasena;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel fondo_form;
    private javax.swing.JLabel imagen_modelo;
    private javax.swing.JLabel inicio_S;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nom_corr1;
    private javax.swing.JSeparator separador1;
    private javax.swing.JLabel tit_contra;
    private javax.swing.JLabel tit_uc;
    private javax.swing.JLabel txt_ingresar;
    // End of variables declaration//GEN-END:variables
}
