/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tiendaderopa.Vistas;

/**
 *
 * @author valen
 */
public class NavBarSLC extends javax.swing.JPanel {

    /**
     * Creates new form NavBarNL
     */
    public NavBarSLC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navbar = new javax.swing.JPanel();
        zafiro = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        icon_usuario = new javax.swing.JLabel();
        nom_usuario = new javax.swing.JLabel();
        icon_bolsa = new javax.swing.JLabel();

        navbar.setBackground(new java.awt.Color(0, 0, 51));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        zafiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiendaderopa/Vistas/imagenes/zafiro_50.jpg"))); // NOI18N
        zafiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navbar.add(zafiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 80));

        titulo.setFont(new java.awt.Font("Sylfaen", 0, 45)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("B  I  E  N  V  E  N  I  D  O");
        titulo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        navbar.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, 80));

        icon_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiendaderopa/Vistas/imagenes/avatar.png"))); // NOI18N
        icon_usuario.setText("jLabel1");
        navbar.add(icon_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 2, 30, 80));

        nom_usuario.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        nom_usuario.setForeground(new java.awt.Color(255, 255, 255));
        nom_usuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nom_usuario.setText("Usuario");
        navbar.add(nom_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 120, 80));

        icon_bolsa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiendaderopa/Vistas/imagenes/bolsa-de-la-compra-blanca.png"))); // NOI18N
        navbar.add(icon_bolsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 2, -1, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, 1290, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icon_bolsa;
    private javax.swing.JLabel icon_usuario;
    private javax.swing.JPanel navbar;
    private javax.swing.JLabel nom_usuario;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel zafiro;
    // End of variables declaration//GEN-END:variables
}
