/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tiendaderopa.Vistas;

/**
 *
 * @author valen
 */
public class PerfilUsuario extends javax.swing.JPanel {

    /**
     * Creates new form PerfilUsuario
     */
    public PerfilUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicio_S1 = new javax.swing.JLabel();
        inicio_S2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        tit_uc1 = new javax.swing.JLabel();
        tit_uc2 = new javax.swing.JLabel();
        nom_corr1 = new javax.swing.JTextField();
        nom_corr = new javax.swing.JTextField();
        separadorC1 = new javax.swing.JSeparator();
        separadorC = new javax.swing.JSeparator();
        tit_uc3 = new javax.swing.JLabel();
        nom_corr2 = new javax.swing.JTextField();
        separadorC2 = new javax.swing.JSeparator();
        tit_uc4 = new javax.swing.JLabel();
        nom_corr3 = new javax.swing.JTextField();
        separadorC3 = new javax.swing.JSeparator();
        separadorC4 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inicio_S1.setFont(new java.awt.Font("Sylfaen", 1, 50)); // NOI18N
        inicio_S1.setForeground(new java.awt.Color(51, 0, 255));
        inicio_S1.setText("Datos personales");
        add(inicio_S1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        inicio_S2.setFont(new java.awt.Font("Sylfaen", 1, 50)); // NOI18N
        inicio_S2.setForeground(new java.awt.Color(51, 0, 255));
        inicio_S2.setText("Acciones");
        add(inicio_S2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 210, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 0, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("PREFERENCIAS");
        jButton1.setBorder(null);
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 390, 201, 54));

        jButton2.setBackground(new java.awt.Color(51, 0, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Actualizar Datos");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 670, 201, 50));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("CERRAR SESIÓN");
        jButton3.setBorder(null);
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 500, 201, 54));

        jButton4.setBackground(new java.awt.Color(51, 0, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("MIS COMPRAS");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 300, 201, 50));

        jPanel2.setBackground(new java.awt.Color(51, 0, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 200, 2, 440));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2000, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 770, 2000, 70));

        tit_uc1.setFont(new java.awt.Font("Yu Gothic UI", 1, 22)); // NOI18N
        tit_uc1.setForeground(new java.awt.Color(51, 0, 255));
        tit_uc1.setText("USUARIO  ");
        add(tit_uc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        tit_uc2.setFont(new java.awt.Font("Yu Gothic UI", 1, 22)); // NOI18N
        tit_uc2.setForeground(new java.awt.Color(51, 0, 255));
        tit_uc2.setText("CORREO");
        add(tit_uc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, -1, -1));

        nom_corr1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        nom_corr1.setForeground(new java.awt.Color(51, 0, 204));
        nom_corr1.setText("Correo electronico");
        nom_corr1.setBorder(null);
        add(nom_corr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 490, -1));

        nom_corr.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        nom_corr.setForeground(new java.awt.Color(51, 0, 204));
        nom_corr.setText("Nombre de Usuario");
        nom_corr.setBorder(null);
        add(nom_corr, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 490, -1));

        separadorC1.setBackground(new java.awt.Color(51, 0, 204));
        separadorC1.setForeground(new java.awt.Color(51, 0, 255));
        add(separadorC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 500, 15));

        separadorC.setBackground(new java.awt.Color(51, 0, 204));
        separadorC.setForeground(new java.awt.Color(51, 0, 255));
        add(separadorC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 500, 15));

        tit_uc3.setFont(new java.awt.Font("Yu Gothic UI", 1, 22)); // NOI18N
        tit_uc3.setForeground(new java.awt.Color(51, 0, 255));
        tit_uc3.setText("CONTRASEÑA");
        add(tit_uc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, -1, -1));

        nom_corr2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        nom_corr2.setForeground(new java.awt.Color(51, 0, 204));
        nom_corr2.setText("*********************");
        nom_corr2.setBorder(null);
        add(nom_corr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, 500, -1));

        separadorC2.setBackground(new java.awt.Color(51, 0, 204));
        separadorC2.setForeground(new java.awt.Color(51, 0, 255));
        add(separadorC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 590, 500, 15));

        tit_uc4.setFont(new java.awt.Font("Yu Gothic UI", 1, 22)); // NOI18N
        tit_uc4.setForeground(new java.awt.Color(51, 0, 255));
        tit_uc4.setText("NOMBRE COMPLETO");
        add(tit_uc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, -1));

        nom_corr3.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        nom_corr3.setForeground(new java.awt.Color(51, 0, 204));
        nom_corr3.setText("Nombre completo del usuario");
        nom_corr3.setBorder(null);
        add(nom_corr3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 490, -1));

        separadorC3.setBackground(new java.awt.Color(51, 0, 204));
        separadorC3.setForeground(new java.awt.Color(51, 0, 255));
        add(separadorC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 500, 15));

        separadorC4.setBackground(new java.awt.Color(51, 0, 204));
        separadorC4.setForeground(new java.awt.Color(51, 0, 255));
        add(separadorC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 500, 15));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel inicio_S1;
    private javax.swing.JLabel inicio_S2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nom_corr;
    private javax.swing.JTextField nom_corr1;
    private javax.swing.JTextField nom_corr2;
    private javax.swing.JTextField nom_corr3;
    private javax.swing.JSeparator separadorC;
    private javax.swing.JSeparator separadorC1;
    private javax.swing.JSeparator separadorC2;
    private javax.swing.JSeparator separadorC3;
    private javax.swing.JSeparator separadorC4;
    private javax.swing.JLabel tit_uc1;
    private javax.swing.JLabel tit_uc2;
    private javax.swing.JLabel tit_uc3;
    private javax.swing.JLabel tit_uc4;
    // End of variables declaration//GEN-END:variables
}
