/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tiendaderopa.Vistas;

import javax.swing.JButton;
import tiendaderopa.Controladores.BolsaCont;
import tiendaderopa.Modelos.Producto;

/**
 *
 * @author valen
 */
public class ProductoBolsa extends javax.swing.JPanel {
    public Producto prod;
    /**
     * Creates new form ProductoCarrito
     */
    
//    public void recibirProducto(Producto producto){
//        this.prod = producto;
//    }
    
    public ProductoBolsa(Producto producto) {
        this.prod = producto;
        initComponents();
        nom_prod.setText(prod.getNombre_prod());
        //consulta de tallas disponibles en la bd para seleccionar una
        precio.setText("$" + prod.getPrecio_prod());
        descripcion_prod.setText("<html>" + prod.getDescipcion_prod() + "</html>");
        
        if (prod.getImg_prod() != null) {
            img_prod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiendaderopa/Vistas/imagenes/imgs_productos/" + prod.getImg_prod())));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cont = new tiendaderopa.Vistas.PanelRound();
        tit_talla = new javax.swing.JLabel();
        talla = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        borrar = new javax.swing.JButton();
        descripcion_prod = new javax.swing.JLabel();
        img_prod = new javax.swing.JLabel();
        nom_prod = new javax.swing.JLabel();

        cont.setBackground(new java.awt.Color(204, 204, 204));
        cont.setRoundBottomLeft(35);
        cont.setRoundBottomRight(35);
        cont.setRoundTopLeft(35);
        cont.setRoundTopRight(35);

        tit_talla.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        tit_talla.setForeground(new java.awt.Color(0, 0, 51));
        tit_talla.setText("Talla:");

        talla.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        talla.setForeground(new java.awt.Color(0, 0, 51));
        talla.setText("N");

        precio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        precio.setForeground(new java.awt.Color(0, 0, 51));
        precio.setText("$$$$$$");

        borrar.setBackground(new java.awt.Color(0, 0, 51));
        borrar.setBorder(null);
        borrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        descripcion_prod.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        descripcion_prod.setText("<html>Es un hecho establecido hace demasiado tiempo que un lector se distraerá con el contenido del texto de un sitio mientras que mira su diseño. El punto de usar Lorem Ipsum es que tiene una distribución más o menos normal de las letras, al contrario de usar textos como por ejemplo \"Contenido aquí, contenido aquí\". Estos textos hacen parecerlo un español que se puede leer. Muchos paquetes de autoedición y editores de páginas web usan el Lorem Ipsum como su texto por defecto, y al hacer una búsqueda de \"Lorem Ipsum\" va a dar por resultado muchos sitios web que usan este texto si se encuentran en estado de desarrollo. Muchas versiones han evolucionado a través de los años, algunas veces por accidente, otras veces a propósito (por ejemplo insertándole humor y cosas por el estilo).</html>");
        descripcion_prod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51), 2));

        img_prod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51)));

        nom_prod.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        nom_prod.setText("Nombre Producto");

        javax.swing.GroupLayout contLayout = new javax.swing.GroupLayout(cont);
        cont.setLayout(contLayout);
        contLayout.setHorizontalGroup(
            contLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(img_prod, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(contLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nom_prod, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(contLayout.createSequentialGroup()
                            .addGroup(contLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(contLayout.createSequentialGroup()
                                    .addComponent(tit_talla, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(talla, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(descripcion_prod, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        contLayout.setVerticalGroup(
            contLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(contLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(img_prod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(contLayout.createSequentialGroup()
                        .addComponent(nom_prod, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descripcion_prod, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(contLayout.createSequentialGroup()
                                .addGroup(contLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(talla, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(contLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(tit_talla, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(precio))
                            .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar;
    private tiendaderopa.Vistas.PanelRound cont;
    private javax.swing.JLabel descripcion_prod;
    private javax.swing.JLabel img_prod;
    private javax.swing.JLabel nom_prod;
    private javax.swing.JLabel precio;
    private javax.swing.JLabel talla;
    private javax.swing.JLabel tit_talla;
    // End of variables declaration//GEN-END:variables

    public JButton getBorrar() {
        return borrar;
    }


}
