/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tiendaderopa.Vistas;
import java.awt.Color;

/**
 *
 * @author josep
 */
public class RegistroUsuario extends javax.swing.JPanel {

    /**
     * Creates new form RegistroUsuario
     */
    public RegistroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo_form = new javax.swing.JPanel();
        inicio_S = new javax.swing.JLabel();
        tit_uc = new javax.swing.JLabel();
        nom_corr = new javax.swing.JTextField();
        separadorNC = new javax.swing.JSeparator();
        tit_contra = new javax.swing.JLabel();
        separadorC = new javax.swing.JSeparator();
        contrasena = new javax.swing.JPasswordField();
        alertaC1 = new javax.swing.JLabel();
        btn_ingresar = new javax.swing.JButton();
        nom_corr1 = new javax.swing.JTextField();
        separadorNC1 = new javax.swing.JSeparator();
        tit_contra1 = new javax.swing.JLabel();
        tit_contra2 = new javax.swing.JLabel();
        separadorC1 = new javax.swing.JSeparator();
        contrasena1 = new javax.swing.JPasswordField();
        alertaC2 = new javax.swing.JLabel();
        tit_uc1 = new javax.swing.JLabel();
        nom_corr2 = new javax.swing.JTextField();
        separadorNC2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        imagen_modelo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo_form.setBackground(new java.awt.Color(0, 0, 51));
        fondo_form.setPreferredSize(new java.awt.Dimension(660, 650));
        fondo_form.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fondo_formMouseEntered(evt);
            }
        });
        fondo_form.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inicio_S.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        inicio_S.setForeground(new java.awt.Color(255, 255, 255));
        inicio_S.setText("REGISTRATE");
        fondo_form.add(inicio_S, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 60));

        tit_uc.setFont(new java.awt.Font("Yu Gothic UI", 1, 22)); // NOI18N
        tit_uc.setForeground(new java.awt.Color(255, 255, 255));
        tit_uc.setText("Nombre Completo  ");
        fondo_form.add(tit_uc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        nom_corr.setBackground(new java.awt.Color(0, 0, 51));
        nom_corr.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        nom_corr.setForeground(new java.awt.Color(153, 153, 153));
        nom_corr.setText("Ingrese su nombre de usuario");
        nom_corr.setBorder(null);
        nom_corr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nom_corrMousePressed(evt);
            }
        });
        nom_corr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_corrActionPerformed(evt);
            }
        });
        fondo_form.add(nom_corr, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 570, 37));

        separadorNC.setBackground(new java.awt.Color(153, 153, 153));
        separadorNC.setForeground(new java.awt.Color(153, 153, 153));
        fondo_form.add(separadorNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 570, 20));

        tit_contra.setFont(new java.awt.Font("Yu Gothic UI", 1, 22)); // NOI18N
        tit_contra.setForeground(new java.awt.Color(255, 255, 255));
        tit_contra.setText("Confirmar Contraseña");
        fondo_form.add(tit_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        separadorC.setBackground(new java.awt.Color(153, 153, 153));
        separadorC.setForeground(new java.awt.Color(153, 153, 153));
        fondo_form.add(separadorC, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 570, 10));

        contrasena.setBackground(new java.awt.Color(0, 0, 51));
        contrasena.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        contrasena.setForeground(new java.awt.Color(153, 153, 153));
        contrasena.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        contrasena.setText("Ingrese su contraseña");
        contrasena.setBorder(null);
        contrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contrasenaMousePressed(evt);
            }
        });
        fondo_form.add(contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 570, 37));

        alertaC1.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        alertaC1.setForeground(new java.awt.Color(0, 0, 51));
        alertaC1.setText("Alerta contraseña");
        fondo_form.add(alertaC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 570, -1));

        btn_ingresar.setBackground(new java.awt.Color(250, 250, 250));
        btn_ingresar.setFont(new java.awt.Font("SimSun", 1, 20)); // NOI18N
        btn_ingresar.setForeground(new java.awt.Color(0, 0, 51));
        btn_ingresar.setText("REGISTRAR");
        btn_ingresar.setBorder(null);
        btn_ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ingresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ingresarMouseExited(evt);
            }
        });
        fondo_form.add(btn_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 150, 49));

        nom_corr1.setBackground(new java.awt.Color(0, 0, 51));
        nom_corr1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        nom_corr1.setForeground(new java.awt.Color(153, 153, 153));
        nom_corr1.setText("Ingrese su correo electronico");
        nom_corr1.setBorder(null);
        nom_corr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nom_corr1MousePressed(evt);
            }
        });
        nom_corr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_corr1ActionPerformed(evt);
            }
        });
        fondo_form.add(nom_corr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 570, 37));

        separadorNC1.setBackground(new java.awt.Color(153, 153, 153));
        separadorNC1.setForeground(new java.awt.Color(153, 153, 153));
        fondo_form.add(separadorNC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 570, -1));

        tit_contra1.setFont(new java.awt.Font("Yu Gothic UI", 1, 22)); // NOI18N
        tit_contra1.setForeground(new java.awt.Color(255, 255, 255));
        tit_contra1.setText("Correo Electronico");
        fondo_form.add(tit_contra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        tit_contra2.setFont(new java.awt.Font("Yu Gothic UI", 1, 22)); // NOI18N
        tit_contra2.setForeground(new java.awt.Color(255, 255, 255));
        tit_contra2.setText("Contraseña");
        fondo_form.add(tit_contra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        separadorC1.setBackground(new java.awt.Color(153, 153, 153));
        separadorC1.setForeground(new java.awt.Color(153, 153, 153));
        fondo_form.add(separadorC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 570, 10));

        contrasena1.setBackground(new java.awt.Color(0, 0, 51));
        contrasena1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        contrasena1.setForeground(new java.awt.Color(153, 153, 153));
        contrasena1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        contrasena1.setText("Ingrese su contraseña");
        contrasena1.setBorder(null);
        contrasena1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contrasena1MousePressed(evt);
            }
        });
        fondo_form.add(contrasena1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 570, 37));

        alertaC2.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        alertaC2.setForeground(new java.awt.Color(0, 0, 51));
        alertaC2.setText("Alerta contraseña");
        fondo_form.add(alertaC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 570, -1));

        tit_uc1.setFont(new java.awt.Font("Yu Gothic UI", 1, 22)); // NOI18N
        tit_uc1.setForeground(new java.awt.Color(255, 255, 255));
        tit_uc1.setText("Nombre Usuario  ");
        fondo_form.add(tit_uc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        nom_corr2.setBackground(new java.awt.Color(0, 0, 51));
        nom_corr2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        nom_corr2.setForeground(new java.awt.Color(153, 153, 153));
        nom_corr2.setText("Ingrese su nombre de usuario");
        nom_corr2.setBorder(null);
        nom_corr2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nom_corr2MousePressed(evt);
            }
        });
        nom_corr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_corr2ActionPerformed(evt);
            }
        });
        fondo_form.add(nom_corr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 570, 37));

        separadorNC2.setBackground(new java.awt.Color(153, 153, 153));
        separadorNC2.setForeground(new java.awt.Color(153, 153, 153));
        fondo_form.add(separadorNC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 570, 10));

        add(fondo_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 650));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiendaderopa/Vistas/imagenes/logo_zafiro.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, 580, 90));

        imagen_modelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiendaderopa/Vistas/imagenes/foto_modelo2.jpg"))); // NOI18N
        add(imagen_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, -160, 800, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nom_corrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nom_corrMousePressed
        // TODO add your handling code here:
        if(nom_corr.getText().equals("Ingrese su nombre de usuario o correo electronico")){
            nom_corr.setText("");
            nom_corr.setForeground(Color.white);
            separadorNC.setForeground(Color.white);
        }
        if(String.valueOf(contrasena.getPassword()).isEmpty()){
            contrasena.setText("Ingrese su contraseña");
            contrasena.setForeground(Color.GRAY);
            separadorC.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_nom_corrMousePressed

    private void nom_corrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_corrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_corrActionPerformed

    private void btn_ingresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresarMouseEntered
        // TODO add your handling code here:
        btn_ingresar.setBackground(new java.awt.Color(195,195,195)); // Color gris
    }//GEN-LAST:event_btn_ingresarMouseEntered

    private void btn_ingresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresarMouseExited
        // TODO add your handling code here:
        btn_ingresar.setBackground(new java.awt.Color(255,255,255)); // Color blanco
    }//GEN-LAST:event_btn_ingresarMouseExited

    private void fondo_formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondo_formMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_fondo_formMouseEntered

    private void nom_corr1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nom_corr1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_corr1MousePressed

    private void nom_corr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_corr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_corr1ActionPerformed

    private void contrasena1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contrasena1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasena1MousePressed

    private void nom_corr2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nom_corr2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_corr2MousePressed

    private void nom_corr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_corr2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_corr2ActionPerformed

    private void contrasenaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contrasenaMousePressed
        // TODO add your handling code here:
        if(nom_corr.getText().isEmpty()){
            nom_corr.setText("Ingrese su nombre de usuario o correo electronico");
            nom_corr.setForeground(Color.GRAY);
            separadorNC.setForeground(Color.GRAY);
        }
        if(String.valueOf(contrasena.getPassword()).equals("Ingrese su contraseña")){
            contrasena.setText("");
            contrasena.setForeground(Color.white);
            separadorC.setForeground(Color.white);
        }
    }//GEN-LAST:event_contrasenaMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alertaC1;
    private javax.swing.JLabel alertaC2;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JPasswordField contrasena;
    private javax.swing.JPasswordField contrasena1;
    private javax.swing.JPanel fondo_form;
    private javax.swing.JLabel imagen_modelo;
    private javax.swing.JLabel inicio_S;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nom_corr;
    private javax.swing.JTextField nom_corr1;
    private javax.swing.JTextField nom_corr2;
    private javax.swing.JSeparator separadorC;
    private javax.swing.JSeparator separadorC1;
    private javax.swing.JSeparator separadorNC;
    private javax.swing.JSeparator separadorNC1;
    private javax.swing.JSeparator separadorNC2;
    private javax.swing.JLabel tit_contra;
    private javax.swing.JLabel tit_contra1;
    private javax.swing.JLabel tit_contra2;
    private javax.swing.JLabel tit_uc;
    private javax.swing.JLabel tit_uc1;
    // End of variables declaration//GEN-END:variables
}
