/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tiendaderopa.Vistas;

import java.awt.Color;

/**
 *
 * @author valen
 */
public class RegUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form Login_v2
     */
    public RegUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reg_usu = new javax.swing.JLabel();
        btn_registrar = new javax.swing.JPanel();
        txt_registrar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nom_usu = new javax.swing.JTextField();
        separadorNU = new javax.swing.JSeparator();
        nombre = new javax.swing.JTextField();
        separadorNom = new javax.swing.JSeparator();
        apellidos = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        separadorCorr = new javax.swing.JSeparator();
        separadorApe = new javax.swing.JSeparator();
        numeroCel = new javax.swing.JTextField();
        separadorNumC = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reg_usu.setFont(new java.awt.Font("Sylfaen", 1, 50)); // NOI18N
        reg_usu.setForeground(new java.awt.Color(0, 0, 51));
        reg_usu.setText("REGISTRO  DE  USUARIO");
        add(reg_usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 80));

        btn_registrar.setBackground(new java.awt.Color(0, 0, 51));
        btn_registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_registrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_registrarMouseExited(evt);
            }
        });

        txt_registrar.setFont(new java.awt.Font("SimSun", 1, 20)); // NOI18N
        txt_registrar.setForeground(new java.awt.Color(255, 255, 255));
        txt_registrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_registrar.setText("REGISTRARSE");
        txt_registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_registrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_registrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_registrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_registrarLayout = new javax.swing.GroupLayout(btn_registrar);
        btn_registrar.setLayout(btn_registrarLayout);
        btn_registrarLayout.setHorizontalGroup(
            btn_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_registrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btn_registrarLayout.setVerticalGroup(
            btn_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_registrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txt_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 560, -1, -1));

        nom_usu.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        nom_usu.setForeground(new java.awt.Color(153, 153, 153));
        nom_usu.setText("Nombre De Usuario");
        nom_usu.setBorder(null);
        nom_usu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nom_usuMousePressed(evt);
            }
        });
        nom_usu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_usuActionPerformed(evt);
            }
        });

        separadorNU.setBackground(new java.awt.Color(153, 153, 153));
        separadorNU.setForeground(new java.awt.Color(153, 153, 153));

        nombre.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        nombre.setForeground(new java.awt.Color(153, 153, 153));
        nombre.setText("Nombre(s) ");
        nombre.setBorder(null);
        nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombreMousePressed(evt);
            }
        });
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        separadorNom.setBackground(new java.awt.Color(153, 153, 153));
        separadorNom.setForeground(new java.awt.Color(153, 153, 153));

        apellidos.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        apellidos.setForeground(new java.awt.Color(153, 153, 153));
        apellidos.setText("Apellido(s) ");
        apellidos.setBorder(null);
        apellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                apellidosMousePressed(evt);
            }
        });
        apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidosActionPerformed(evt);
            }
        });

        correo.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        correo.setForeground(new java.awt.Color(153, 153, 153));
        correo.setText("Correo Electronico");
        correo.setBorder(null);
        correo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                correoMousePressed(evt);
            }
        });
        correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoActionPerformed(evt);
            }
        });

        separadorCorr.setBackground(new java.awt.Color(153, 153, 153));
        separadorCorr.setForeground(new java.awt.Color(153, 153, 153));

        separadorApe.setBackground(new java.awt.Color(153, 153, 153));
        separadorApe.setForeground(new java.awt.Color(153, 153, 153));

        numeroCel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        numeroCel.setForeground(new java.awt.Color(153, 153, 153));
        numeroCel.setText("Numero Celular");
        numeroCel.setBorder(null);
        numeroCel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                numeroCelMousePressed(evt);
            }
        });
        numeroCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroCelActionPerformed(evt);
            }
        });

        separadorNumC.setBackground(new java.awt.Color(153, 153, 153));
        separadorNumC.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(separadorApe, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(correo)
                        .addComponent(apellidos)
                        .addComponent(separadorNom)
                        .addComponent(nombre)
                        .addComponent(separadorNU)
                        .addComponent(nom_usu, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                        .addComponent(separadorCorr)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numeroCel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separadorNumC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom_usu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroCel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separadorNU, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separadorNumC, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorNom, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorApe, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separadorCorr, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 1110, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void nom_usuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_usuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_usuActionPerformed

    private void txt_registrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_registrarMouseEntered
        btn_registrar.setBackground(new java.awt.Color(195,195,195)); // Color gris
    }//GEN-LAST:event_txt_registrarMouseEntered

    private void btn_registrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarMouseEntered
       btn_registrar.setBackground(new java.awt.Color(195,195,195)); // Color gris
    }//GEN-LAST:event_btn_registrarMouseEntered

    private void btn_registrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarMouseExited
        // TODO add your handling code here:
        btn_registrar.setBackground(new java.awt.Color(255,255,255)); // Color blanco
    }//GEN-LAST:event_btn_registrarMouseExited

    private void txt_registrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_registrarMouseExited
        // TODO add your handling code here:
        btn_registrar.setBackground(new java.awt.Color(255,255,255)); // Color blanco
    }//GEN-LAST:event_txt_registrarMouseExited

    private void nom_usuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nom_usuMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_usuMousePressed

    private void txt_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_registrarMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_registrarMouseClicked

    private void nombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreMousePressed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void apellidosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apellidosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidosMousePressed

    private void apellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidosActionPerformed

    private void correoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_correoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoMousePressed

    private void correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoActionPerformed

    private void numeroCelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numeroCelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroCelMousePressed

    private void numeroCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroCelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroCelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidos;
    private javax.swing.JPanel btn_registrar;
    private javax.swing.JTextField correo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nom_usu;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField numeroCel;
    private javax.swing.JLabel reg_usu;
    private javax.swing.JSeparator separadorApe;
    private javax.swing.JSeparator separadorCorr;
    private javax.swing.JSeparator separadorNU;
    private javax.swing.JSeparator separadorNom;
    private javax.swing.JSeparator separadorNumC;
    private javax.swing.JLabel txt_registrar;
    // End of variables declaration//GEN-END:variables
}
