/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tiendaderopa.Vistas;

import java.awt.Color;

/**
 *
 * @author valen
 */
public class RegUsuario extends javax.swing.JPanel {

    /**
     * Creates new form Login_v2
     */
    public RegUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo_form = new javax.swing.JPanel();
        inicio_S = new javax.swing.JLabel();
        tit_Nom = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        separadorN = new javax.swing.JSeparator();
        tit_NomU = new javax.swing.JLabel();
        nomUsu = new javax.swing.JTextField();
        separadorNU = new javax.swing.JSeparator();
        tit_correo = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        separadorCor = new javax.swing.JSeparator();
        tit_cont = new javax.swing.JLabel();
        contrasena = new javax.swing.JPasswordField();
        separadorCont = new javax.swing.JSeparator();
        tit_confCont = new javax.swing.JLabel();
        confContrasena = new javax.swing.JPasswordField();
        separadorCCont = new javax.swing.JSeparator();
        btn_registrar = new javax.swing.JPanel();
        txt_registrar = new javax.swing.JLabel();
        zafiro = new javax.swing.JLabel();
        imagen_modelo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo_form.setBackground(new java.awt.Color(255, 255, 255));
        fondo_form.setPreferredSize(new java.awt.Dimension(660, 650));

        inicio_S.setFont(new java.awt.Font("Sylfaen", 1, 40)); // NOI18N
        inicio_S.setForeground(new java.awt.Color(0, 0, 51));
        inicio_S.setText("REGISTRO");

        tit_Nom.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        tit_Nom.setForeground(new java.awt.Color(0, 0, 51));
        tit_Nom.setText("NOMBRE COMPLETO");

        nombre.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        nombre.setForeground(new java.awt.Color(153, 153, 153));
        nombre.setText("Ingrese su nombre completo");
        nombre.setBorder(null);
        nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombreMousePressed(evt);
            }
        });
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        separadorN.setBackground(new java.awt.Color(153, 153, 153));
        separadorN.setForeground(new java.awt.Color(153, 153, 153));

        tit_NomU.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        tit_NomU.setForeground(new java.awt.Color(0, 0, 51));
        tit_NomU.setText("NOMBRE DE USUARIO");

        nomUsu.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        nomUsu.setForeground(new java.awt.Color(153, 153, 153));
        nomUsu.setText("Ingrese su nombre de usuario");
        nomUsu.setBorder(null);
        nomUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nomUsuMousePressed(evt);
            }
        });
        nomUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomUsuActionPerformed(evt);
            }
        });

        separadorNU.setBackground(new java.awt.Color(153, 153, 153));
        separadorNU.setForeground(new java.awt.Color(153, 153, 153));

        tit_correo.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        tit_correo.setForeground(new java.awt.Color(0, 0, 51));
        tit_correo.setText("CORREO");

        correo.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        correo.setForeground(new java.awt.Color(153, 153, 153));
        correo.setText("Ingrese su nombre de usuario");
        correo.setBorder(null);
        correo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                correoMousePressed(evt);
            }
        });
        correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoActionPerformed(evt);
            }
        });

        separadorCor.setBackground(new java.awt.Color(153, 153, 153));
        separadorCor.setForeground(new java.awt.Color(153, 153, 153));

        tit_cont.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        tit_cont.setForeground(new java.awt.Color(0, 0, 51));
        tit_cont.setText("CONTRASEÑA");

        contrasena.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        contrasena.setForeground(new java.awt.Color(153, 153, 153));
        contrasena.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        contrasena.setText("Ingrese su contraseña");
        contrasena.setBorder(null);

        separadorCont.setBackground(new java.awt.Color(153, 153, 153));
        separadorCont.setForeground(new java.awt.Color(153, 153, 153));

        tit_confCont.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        tit_confCont.setForeground(new java.awt.Color(0, 0, 51));
        tit_confCont.setText("CONFIRMAR CONTRASEÑA");

        confContrasena.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        confContrasena.setForeground(new java.awt.Color(153, 153, 153));
        confContrasena.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        confContrasena.setText("Ingrese su contraseña");
        confContrasena.setBorder(null);

        separadorCCont.setBackground(new java.awt.Color(153, 153, 153));
        separadorCCont.setForeground(new java.awt.Color(153, 153, 153));

        btn_registrar.setBackground(new java.awt.Color(0, 0, 51));
        btn_registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_registrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_registrarMouseExited(evt);
            }
        });

        txt_registrar.setFont(new java.awt.Font("SimSun", 1, 20)); // NOI18N
        txt_registrar.setForeground(new java.awt.Color(255, 255, 255));
        txt_registrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_registrar.setText("REGISTRARSE");
        txt_registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_registrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_registrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_registrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_registrarLayout = new javax.swing.GroupLayout(btn_registrar);
        btn_registrar.setLayout(btn_registrarLayout);
        btn_registrarLayout.setHorizontalGroup(
            btn_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_registrar, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
        );
        btn_registrarLayout.setVerticalGroup(
            btn_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_registrar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fondo_formLayout = new javax.swing.GroupLayout(fondo_form);
        fondo_form.setLayout(fondo_formLayout);
        fondo_formLayout.setHorizontalGroup(
            fondo_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondo_formLayout.createSequentialGroup()
                .addGroup(fondo_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondo_formLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(inicio_S))
                    .addGroup(fondo_formLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(fondo_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tit_confCont)
                            .addComponent(separadorCCont, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                            .addComponent(tit_cont)
                            .addComponent(separadorCont, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                            .addComponent(tit_correo)
                            .addComponent(correo, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                            .addComponent(separadorCor, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                            .addComponent(tit_NomU)
                            .addComponent(nomUsu, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                            .addComponent(separadorNU, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                            .addComponent(tit_Nom)
                            .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                            .addComponent(separadorN, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                            .addComponent(confContrasena)
                            .addComponent(contrasena))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        fondo_formLayout.setVerticalGroup(
            fondo_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondo_formLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(inicio_S, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tit_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorN, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tit_NomU, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorNU, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tit_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorCor, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tit_cont, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorCont, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(tit_confCont, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorCCont, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        add(fondo_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 650));

        zafiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiendaderopa/Vistas/imagenes/logo_zafiro.png"))); // NOI18N
        add(zafiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, -1, 110));

        imagen_modelo.setBackground(new java.awt.Color(255, 255, 255));
        imagen_modelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiendaderopa/Vistas/imagenes/foto_modelo2.jpg"))); // NOI18N
        add(imagen_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, -160, 780, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_registrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_registrarMouseEntered
        btn_registrar.setBackground(new java.awt.Color(195,195,195)); // Color gris
        txt_registrar.setForeground(new Color(0, 0, 51)); //color azul
    }//GEN-LAST:event_txt_registrarMouseEntered

    private void btn_registrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarMouseEntered
       btn_registrar.setBackground(new java.awt.Color(195,195,195)); // Color gris
       txt_registrar.setForeground(new Color(0, 0, 51)); //color azul
    }//GEN-LAST:event_btn_registrarMouseEntered

    private void btn_registrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarMouseExited
        // TODO add your handling code here:
        btn_registrar.setBackground(new java.awt.Color(0,0,51)); // Color azul
        txt_registrar.setForeground(new Color(255, 255, 255)); //color blanco
    }//GEN-LAST:event_btn_registrarMouseExited

    private void txt_registrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_registrarMouseExited
        // TODO add your handling code here:
        btn_registrar.setBackground(new java.awt.Color(0,0,51)); // Color azul
        txt_registrar.setForeground(new Color(255, 255, 255)); //color blanco
    }//GEN-LAST:event_txt_registrarMouseExited

    private void txt_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_registrarMouseClicked
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this,"credencial de ingreso: " + nombre.getText() + "\n Contraseña: " + String.valueOf( contrasena.getPassword()));
    }//GEN-LAST:event_txt_registrarMouseClicked

    private void nombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreMousePressed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void nomUsuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomUsuMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomUsuMousePressed

    private void nomUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomUsuActionPerformed

    private void correoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_correoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoMousePressed

    private void correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_registrar;
    private javax.swing.JPasswordField confContrasena;
    private javax.swing.JPasswordField contrasena;
    private javax.swing.JTextField correo;
    private javax.swing.JPanel fondo_form;
    private javax.swing.JLabel imagen_modelo;
    private javax.swing.JLabel inicio_S;
    private javax.swing.JTextField nomUsu;
    private javax.swing.JTextField nombre;
    private javax.swing.JSeparator separadorCCont;
    private javax.swing.JSeparator separadorCont;
    private javax.swing.JSeparator separadorCor;
    private javax.swing.JSeparator separadorN;
    private javax.swing.JSeparator separadorNU;
    private javax.swing.JLabel tit_Nom;
    private javax.swing.JLabel tit_NomU;
    private javax.swing.JLabel tit_confCont;
    private javax.swing.JLabel tit_cont;
    private javax.swing.JLabel tit_correo;
    private javax.swing.JLabel txt_registrar;
    private javax.swing.JLabel zafiro;
    // End of variables declaration//GEN-END:variables
}
